### ISSUE TITLE
Not clear how to extract options when a sub-command is involved?

### ISSUE THREAD

**Issue by salgit** [dr1fter/cli-parsec#1]
I have an options class which looks something like this:

public class CLIOptions {

```
@HelpOption
boolean help; //help defaults to '--help'/'-h'

@Option(shortOption='c')
String common = "common";

@Command(name="sub")
SubArgs sub;

static class SubArgs {
    @HelpOption
    boolean help; //help defaults to '--help'/'-h'

    @Option
    String foo = "bar"
}
```

}

When I try to parse it out like so:

ParsingResult<CLIOptions> parseResult = CliParser.createCliParser().parse(new CLIOptions(), args);

I find that if I actually invoked the program with a sub-command, e.g.:

java -jar myjar.jar -c foo1 sub --foo bar2

then I cannot extract options like so:

CLIOptions opts = parseResult.options();

The JVM complains that it cannot cast CLIOptions$SubArgs to CLIOptions. Looking at the code for the parser, it is not clear how it chains options? IOW, not clear how to get this going? The Java compiler will not let me cast the result of parseResult.options() to CLIOptions.SubArgs either, i.e:

CLIOptions.SubArgs opts = (CLIOptions.SubArgs) parseResult.options();

Is there a class hierarchy which should be used for options classes in order to make them work? Or am I missing something else?

**Comment by dr1fter** [comment]
I guess this part of the interface I did not think through 100%, so thanks for your feedback.

After the parser returns, the CLIOptions instance you passed in will be initialised with the parsed values (this was the original interface I aimed for). So instead of passing in an anonymous instance of CLIOptions, you could do this:

``` java
CLIOptions options = new CLIOptions()
CliParser.createCliParser().parse(options, args);
//from this point on, options is initialised according to given args
// (including the SubArgs sub field in your example)
```

In the case of nested commands, you will of course still need to know which sub-command was chosen. This is what I intended the ParsingResult for. ParsingResult contains the chain of nested commands from first to last (selectedCommand / nestedCommand). Since you already can access the option object from top using the initial options instance, I thought it to be convenient to also be able to access the deepest-nested options object as a short-cut from the ParsingResult as well.

It might be a bit tricky, but if I find the time, I might look into changing the ParsingResult in such a way that it also contains the corresponding option objects.

I hope I could answer your initial question and would be glad to hear whether the lib fits your needs.

**Comment by salgit** [comment]
I just realized I never closed the issue out, or thanked you for your prompt response :) the library is great and one of the most complete ones I found! Thank you for putting your work out there.

**Comment by dr1fter** [comment]
Thanks for finally closing the issue; I'm happy that you like my library :-)
